name: crewai_qwen
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.11.12
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pywin32=307
  - pyzmq=26.4.0
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - alembic==1.15.2
      - anyio==4.9.0
      - appdirs==1.4.4
      - asgiref==3.8.1
      - attrs==25.3.0
      - auth0-python==4.9.0
      - av==14.4.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - chroma-hnswlib==0.7.6
      - chromadb==1.0.9
      - click==8.1.8
      - cohere==5.15.0
      - coloredlogs==15.0.1
      - crewai==0.120.1
      - cryptography==45.0.2
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - deprecated==1.2.18
      - deprecation==2.1.0
      - dill==0.3.8
      - distro==1.9.0
      - docker==7.1.0
      - docstring-parser==0.16
      - duckduckgo-search==8.0.2
      - durationpy==0.10
      - et-xmlfile==2.0.0
      - fastapi==0.115.9
      - fastavro==1.11.1
      - flatbuffers==25.2.10
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - google-auth==2.40.1
      - googleapis-common-protos==1.70.0
      - gptcache==0.1.44
      - greenlet==3.2.2
      - grpcio==1.71.0
      - h11==0.16.0
      - h2==4.2.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.31.4
      - humanfriendly==10.0
      - hyperframe==6.1.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - instructor==1.8.2
      - jiter==0.8.2
      - json-repair==0.44.1
      - json5==0.12.0
      - jsonpatch==1.33
      - jsonpickle==4.0.5
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kubernetes==32.0.1
      - lancedb==0.22.0
      - langchain==0.3.25
      - langchain-cohere==0.3.5
      - langchain-community==0.3.24
      - langchain-core==0.3.60
      - langchain-experimental==0.3.4
      - langchain-openai==0.2.14
      - langchain-text-splitters==0.3.8
      - langsmith==0.3.42
      - lazy-loader==0.4
      - litellm==1.68.0
      - lmdb==1.6.2
      - lxml==5.4.0
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mem0ai==0.1.100
      - mmh3==5.1.0
      - monotonic==1.6
      - multidict==6.4.4
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - nodeenv==1.9.1
      - numpy==2.2.6
      - oauthlib==3.2.2
      - onnxruntime==1.22.0
      - openai==1.75.0
      - openpyxl==3.1.5
      - opentelemetry-api==1.33.1
      - opentelemetry-exporter-otlp-proto-common==1.33.1
      - opentelemetry-exporter-otlp-proto-grpc==1.33.1
      - opentelemetry-exporter-otlp-proto-http==1.33.1
      - opentelemetry-instrumentation==0.54b1
      - opentelemetry-instrumentation-asgi==0.54b1
      - opentelemetry-instrumentation-fastapi==0.54b1
      - opentelemetry-proto==1.33.1
      - opentelemetry-sdk==1.33.1
      - opentelemetry-semantic-conventions==0.54b1
      - opentelemetry-util-http==0.54b1
      - orjson==3.10.18
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pdfminer-six==20250327
      - pdfplumber==0.11.6
      - pillow==11.2.1
      - pip==25.1.1
      - portalocker==2.10.1
      - posthog==3.25.0
      - primp==0.15.0
      - propcache==0.3.1
      - protobuf==5.29.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic-settings==2.9.1
      - pyjwt==2.10.1
      - pymupdf==1.25.5
      - pypdf==5.5.0
      - pypdfium2==4.30.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - pyright==1.1.400
      - pysbd==0.3.4
      - python-dotenv==1.1.0
      - pytube==15.0.0
      - pytz==2024.2
      - pyvis==0.3.2
      - pyyaml==6.0.2
      - qdrant-client==1.14.2
      - qwen-vl-utils==0.0.11
      - rapidfuzz==3.13.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.25.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - schema==0.7.7
      - scikit-image==0.25.2
      - scipy==1.15.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - starlette==0.45.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tifffile==2025.5.10
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - tomli-w==1.2.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.51.3
      - typer==0.15.4
      - types-requests==2.32.0.20250515
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - uv==0.7.6
      - uvicorn==0.34.2
      - watchfiles==1.0.5
      - websocket-client==1.8.0
      - websockets==15.0.1
      - wikipedia==1.4.0
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.0
      - zstandard==0.23.0
